### ISSUE TITLE
Policy is not saved

### ISSUE THREAD

**Issue by dohaicuong** [node-casbin/prisma-adapter#12]
## Bug description
After running enforcer.savePolicy() and restart the service. Previous adding policy is not saved

## Details
I setup the enforcer to use prisma-adapter

```js
export const getEnforcer = async () => {
  const a = await PrismaAdapter.newAdapter()
  const e = await casbin.newEnforcer(`${__dirname}/rbac_model.conf`, a)
  e.enableAutoSave(true)

  return e
}
```

and add role for user
```js
await enforcer.addRoleForUser(newUser.id, 'user')
```

but the data didn't save to prisma as when I restart the server and check userRoles it returns empty array of roles
```js
const roles = await enforcer.getRolesForUser(userId)
```

even when I do manual save
```js
await enforcer.savePolicy()
```

**Comment by hsluoyz** [comment]
@nodece @zhmushan can anyone take this issue?

**Comment by dohaicuong** [comment]
Hi @hsluoyz,
thank you for quick reply
Just realise it's problem coming from my casbin setup :)
So I will just close the issue

sorry for the trouble
