### ISSUE TITLE
Test, CI, code coverage, badges and NPM

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/prisma-adapter#2]
Great job! @zhmushan 

I just list some remaining items to be done.

**Comment by zhmushan** [comment]
Okay, I am trying to automatically post to `npm`.

**Comment by hsluoyz** [comment]
@zhmushan is there any progress for this repo?

**Comment by nodece** [comment]
@hsluoyz  casbin-prisma-adapter has been released on NPM.
