### ISSUE TITLE
Allow Prisma client to be set on constructor

### ISSUE THREAD

**Issue by dimino** [node-casbin/prisma-adapter#24]
Would it be possible to allow for the Prisma client to get set/managed outside of the adapter?  I think it'd be as simple as allowing the Prisma client to get set as an optional constructor arg:

```typescript
  constructor(option?: Prisma.PrismaClientOptions, prismaClient?: PrismaClient) {
    this.#option = option;
    this.#prisma = prismaClient;
  }
```

...or something like that.  Forgive me for my potentially bad TS!

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
OK, we will add this.

**Comment by hsluoyz** [comment]
@Zxilly plz make a new release.
