### ISSUE TITLE
[BUG] How to support a specified directory for the Prisma Client?

### ISSUE THREAD

**Issue by Lce-Lemon** [node-casbin/prisma-adapter#53]
When I modify the generated directory for Prisma, the adapter doesn't work properly.

**Comment by hsluoyz** [comment]
@Lce-Lemon Prisma is an ORM, what do you mean by the "generated directory for Prisma"? Can you provide a full example code?

**Comment by Lce-Lemon** [comment]
> Prisma is an ORM, what do you mean by the "generated directory for Prisma"? Can you provide a full example code?

Please look [here](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#specify-a-custom-output-location-for-prisma-client)

**Comment by hsluoyz** [comment]
Then I think we can provide an optional argument in this adapter to allow users to specify the directory for the Prisma Client

**Comment by tx2002** [comment]
@Lce-Lemon  Thank you for your feedback! Adapting to a custom generator output path is quite challenging for us. We would suggest modifying the source code of the casbin-prisma-adapter manually to import the relevant Prisma generator classes from your custom output path.
https://github.com/search?q=repo%3Anode-casbin/prisma-adapter%20%27%40prisma/client%27&type=code

**Comment by hsluoyz** [comment]
Closed as resolved
