### ISSUE TITLE
Testing adapter

### ISSUE THREAD

**Issue by rgarcia3pillar** [node-casbin/prisma-adapter#59]
I am integrating the adapter with `fastify-casbin`.

When creating a unit test for the adapter I get the error _"PrismaClientInitializationError: error: Environment variable not found: DATABASE_URL."_

I am mocking prisma client using `vitest-mock-extended`

**Comment by hsluoyz** [comment]
@rgarcia3pillar can you give more details?

**Comment by hsluoyz** [comment]
@rgarcia3pillar then define the `DATABASE_URL` env var in your test?

**Comment by hsluoyz** [comment]
Closed as stale
